export const UPDATE_USER_NAME = "UPDATE_USER_NAME";
export const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const UPDATE_USER_PHONE_NUMBER = "UPDATE_USER_PHONE_NUMBER";
export const UPDATE_USER_EDUCATION = "UPDATE_USER_EDUCATION";
export const UPDATE_USER_EXPERIENCE = "UPDATE_USER_EXPERIENCE"
